document:
  name: La carta dei principi per la condotta tecnologica
  description: |
    Questo repository contiene il testo della carta dei principi per la di condotta tecnologica:
    autoregolamentazione ed etica  per un nuovo rapporto tra fornitori di
    tecnologia e la Pubblica Amministrazione.
  tags:
    - procurement
    - tecnologica
