document:
  name: Codice di condotta tecnologica
  description: |
    Questo repository contiene il testo del codice di condotta tecnologica:
    autoregolamentazione ed etica  per un nuovo rapporto tra fornitori di
    tecnologia e la Pubblica Amministrazione.
  tags:
    - procurement
    - tecnologica
